package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1



/**
 * ContactUsTable generated by hbm2java
 */
public class ContactUsTable  implements java.io.Serializable {


     private int contactId;
     private String name;
     private String email;
     private String mobile;
     private String subject;
     private String msg;

    public ContactUsTable() {
    }

	
    public ContactUsTable(int contactId) {
        this.contactId = contactId;
    }
    public ContactUsTable(int contactId, String name, String email, String mobile, String subject, String msg) {
       this.contactId = contactId;
       this.name = name;
       this.email = email;
       this.mobile = mobile;
       this.subject = subject;
       this.msg = msg;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }




}


