package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1



/**
 * DesignationTable generated by hbm2java
 */
public class DesignationTable  implements java.io.Serializable {


     private int degId;
     private String designationName;
     private String gread;
     private Float salary;

    public DesignationTable() {
    }

	
    public DesignationTable(int degId) {
        this.degId = degId;
    }
    public DesignationTable(int degId, String designationName, String gread, Float salary) {
       this.degId = degId;
       this.designationName = designationName;
       this.gread = gread;
       this.salary = salary;
    }
   
    public int getDegId() {
        return this.degId;
    }
    
    public void setDegId(int degId) {
        this.degId = degId;
    }
    public String getDesignationName() {
        return this.designationName;
    }
    
    public void setDesignationName(String designationName) {
        this.designationName = designationName;
    }
    public String getGread() {
        return this.gread;
    }
    
    public void setGread(String gread) {
        this.gread = gread;
    }
    public Float getSalary() {
        return this.salary;
    }
    
    public void setSalary(Float salary) {
        this.salary = salary;
    }




}


