package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EmpInfo generated by hbm2java
 */
public class EmpInfo  implements java.io.Serializable {


     private String empId;
     private String firstname;
     private String lastname;
     private String gender;
     private String jobTitle;
     private String department;
     private Date dob;
     private String nationality;
     private String email;
     private String contact;
     private String mailAddress;
     private Set salaryInfos = new HashSet(0);
     private Set extraActivityTables = new HashSet(0);
     private Set performanceTables = new HashSet(0);
     private FamilyInfo familyInfo;
     private Set leaveInfos = new HashSet(0);
     private Set taskTables = new HashSet(0);
     private Set promotiomTables = new HashSet(0);

    public EmpInfo() {
    }

	
    public EmpInfo(String empId, String lastname, Date dob, String nationality) {
        this.empId = empId;
        this.lastname = lastname;
        this.dob = dob;
        this.nationality = nationality;
    }
    public EmpInfo(String empId, String firstname, String lastname, String gender, String jobTitle, String department, Date dob, String nationality, String email, String contact, String mailAddress, Set salaryInfos, Set extraActivityTables, Set performanceTables, FamilyInfo familyInfo, Set leaveInfos, Set taskTables, Set promotiomTables) {
       this.empId = empId;
       this.firstname = firstname;
       this.lastname = lastname;
       this.gender = gender;
       this.jobTitle = jobTitle;
       this.department = department;
       this.dob = dob;
       this.nationality = nationality;
       this.email = email;
       this.contact = contact;
       this.mailAddress = mailAddress;
       this.salaryInfos = salaryInfos;
       this.extraActivityTables = extraActivityTables;
       this.performanceTables = performanceTables;
       this.familyInfo = familyInfo;
       this.leaveInfos = leaveInfos;
       this.taskTables = taskTables;
       this.promotiomTables = promotiomTables;
    }
   
    public String getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(String empId) {
        this.empId = empId;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getMailAddress() {
        return this.mailAddress;
    }
    
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }
    public Set getSalaryInfos() {
        return this.salaryInfos;
    }
    
    public void setSalaryInfos(Set salaryInfos) {
        this.salaryInfos = salaryInfos;
    }
    public Set getExtraActivityTables() {
        return this.extraActivityTables;
    }
    
    public void setExtraActivityTables(Set extraActivityTables) {
        this.extraActivityTables = extraActivityTables;
    }
    public Set getPerformanceTables() {
        return this.performanceTables;
    }
    
    public void setPerformanceTables(Set performanceTables) {
        this.performanceTables = performanceTables;
    }
    public FamilyInfo getFamilyInfo() {
        return this.familyInfo;
    }
    
    public void setFamilyInfo(FamilyInfo familyInfo) {
        this.familyInfo = familyInfo;
    }
    public Set getLeaveInfos() {
        return this.leaveInfos;
    }
    
    public void setLeaveInfos(Set leaveInfos) {
        this.leaveInfos = leaveInfos;
    }
    public Set getTaskTables() {
        return this.taskTables;
    }
    
    public void setTaskTables(Set taskTables) {
        this.taskTables = taskTables;
    }
    public Set getPromotiomTables() {
        return this.promotiomTables;
    }
    
    public void setPromotiomTables(Set promotiomTables) {
        this.promotiomTables = promotiomTables;
    }




}


