package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1



/**
 * ExtraActivityTable generated by hbm2java
 */
public class ExtraActivityTable  implements java.io.Serializable {


     private Integer activityId;
     private EmpInfo empInfo;
     private String purpose;
     private Float announcementAmount;
     private String notes;

    public ExtraActivityTable() {
    }

	
    public ExtraActivityTable(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }
    public ExtraActivityTable(EmpInfo empInfo, String purpose, Float announcementAmount, String notes) {
       this.empInfo = empInfo;
       this.purpose = purpose;
       this.announcementAmount = announcementAmount;
       this.notes = notes;
    }
   
    public Integer getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    public EmpInfo getEmpInfo() {
        return this.empInfo;
    }
    
    public void setEmpInfo(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    public Float getAnnouncementAmount() {
        return this.announcementAmount;
    }
    
    public void setAnnouncementAmount(Float announcementAmount) {
        this.announcementAmount = announcementAmount;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


