package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1



/**
 * FamilyInfo generated by hbm2java
 */
public class FamilyInfo  implements java.io.Serializable {


     private String empId;
     private EmpInfo empInfo;
     private String nominyName;
     private String relation;
     private String contact;
     private String mailAddress;
     private String email;

    public FamilyInfo() {
    }

	
    public FamilyInfo(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }
    public FamilyInfo(EmpInfo empInfo, String nominyName, String relation, String contact, String mailAddress, String email) {
       this.empInfo = empInfo;
       this.nominyName = nominyName;
       this.relation = relation;
       this.contact = contact;
       this.mailAddress = mailAddress;
       this.email = email;
    }
   
    public String getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(String empId) {
        this.empId = empId;
    }
    public EmpInfo getEmpInfo() {
        return this.empInfo;
    }
    
    public void setEmpInfo(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }
    public String getNominyName() {
        return this.nominyName;
    }
    
    public void setNominyName(String nominyName) {
        this.nominyName = nominyName;
    }
    public String getRelation() {
        return this.relation;
    }
    
    public void setRelation(String relation) {
        this.relation = relation;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getMailAddress() {
        return this.mailAddress;
    }
    
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


