package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LeaveInfo generated by hbm2java
 */
public class LeaveInfo  implements java.io.Serializable {


     private Integer leaveId;
     private EmpInfo empInfo;
     private String reason;
     private Date fromDate;
     private Date toDate;
     private Integer noOfDate;

    public LeaveInfo() {
    }

    public LeaveInfo(EmpInfo empInfo, String reason, Date fromDate, Date toDate, Integer noOfDate) {
       this.empInfo = empInfo;
       this.reason = reason;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.noOfDate = noOfDate;
    }
   
    public Integer getLeaveId() {
        return this.leaveId;
    }
    
    public void setLeaveId(Integer leaveId) {
        this.leaveId = leaveId;
    }
    public EmpInfo getEmpInfo() {
        return this.empInfo;
    }
    
    public void setEmpInfo(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public Integer getNoOfDate() {
        return this.noOfDate;
    }
    
    public void setNoOfDate(Integer noOfDate) {
        this.noOfDate = noOfDate;
    }




}


