package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1



/**
 * PerformanceTable generated by hbm2java
 */
public class PerformanceTable  implements java.io.Serializable {


     private Integer performId;
     private EmpInfo empInfo;
     private String month;
     private Integer noOfAssignment;
     private Integer noOfClientDeily;
     private Integer leave;

    public PerformanceTable() {
    }

    public PerformanceTable(EmpInfo empInfo, String month, Integer noOfAssignment, Integer noOfClientDeily, Integer leave) {
       this.empInfo = empInfo;
       this.month = month;
       this.noOfAssignment = noOfAssignment;
       this.noOfClientDeily = noOfClientDeily;
       this.leave = leave;
    }
   
    public Integer getPerformId() {
        return this.performId;
    }
    
    public void setPerformId(Integer performId) {
        this.performId = performId;
    }
    public EmpInfo getEmpInfo() {
        return this.empInfo;
    }
    
    public void setEmpInfo(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    public Integer getNoOfAssignment() {
        return this.noOfAssignment;
    }
    
    public void setNoOfAssignment(Integer noOfAssignment) {
        this.noOfAssignment = noOfAssignment;
    }
    public Integer getNoOfClientDeily() {
        return this.noOfClientDeily;
    }
    
    public void setNoOfClientDeily(Integer noOfClientDeily) {
        this.noOfClientDeily = noOfClientDeily;
    }
    public Integer getLeave() {
        return this.leave;
    }
    
    public void setLeave(Integer leave) {
        this.leave = leave;
    }




}


