package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1



/**
 * SalaryInfo generated by hbm2java
 */
public class SalaryInfo  implements java.io.Serializable {


     private int salaryId;
     private EmpInfo empInfo;
     private Float regularSalary;
     private Float totalSalary;
     private String paymentMethod;
     private String month;

    public SalaryInfo() {
    }

	
    public SalaryInfo(int salaryId) {
        this.salaryId = salaryId;
    }
    public SalaryInfo(int salaryId, EmpInfo empInfo, Float regularSalary, Float totalSalary, String paymentMethod, String month) {
       this.salaryId = salaryId;
       this.empInfo = empInfo;
       this.regularSalary = regularSalary;
       this.totalSalary = totalSalary;
       this.paymentMethod = paymentMethod;
       this.month = month;
    }
   
    public int getSalaryId() {
        return this.salaryId;
    }
    
    public void setSalaryId(int salaryId) {
        this.salaryId = salaryId;
    }
    public EmpInfo getEmpInfo() {
        return this.empInfo;
    }
    
    public void setEmpInfo(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }
    public Float getRegularSalary() {
        return this.regularSalary;
    }
    
    public void setRegularSalary(Float regularSalary) {
        this.regularSalary = regularSalary;
    }
    public Float getTotalSalary() {
        return this.totalSalary;
    }
    
    public void setTotalSalary(Float totalSalary) {
        this.totalSalary = totalSalary;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }




}


