package com.pojo;
// Generated Nov 30, 2016 8:49:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TaskTable generated by hbm2java
 */
public class TaskTable  implements java.io.Serializable {


     private String taskId;
     private EmpInfo empInfo;
     private String taskTitle;
     private Date startDate;
     private Date endDate;
     private String remarks;

    public TaskTable() {
    }

	
    public TaskTable(String taskId) {
        this.taskId = taskId;
    }
    public TaskTable(String taskId, EmpInfo empInfo, String taskTitle, Date startDate, Date endDate, String remarks) {
       this.taskId = taskId;
       this.empInfo = empInfo;
       this.taskTitle = taskTitle;
       this.startDate = startDate;
       this.endDate = endDate;
       this.remarks = remarks;
    }
   
    public String getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
    public EmpInfo getEmpInfo() {
        return this.empInfo;
    }
    
    public void setEmpInfo(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }
    public String getTaskTitle() {
        return this.taskTitle;
    }
    
    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


